//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  authentication: Authentication;
  authenticationConnection: AuthenticationConnection;
  webHosting: WebHosting;
  webHostingConnection: WebHostingConnection;
  baas: Baas;
  baasConnection: BaasConnection;
  cloudProviders: CloudProviders;
  cloudProvidersConnection: CloudProvidersConnection;
  frameworks: Frameworks;
  frameworksConnection: FrameworksConnection;
  paas: Paas;
  paasConnection: PaasConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAuthenticationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAuthenticationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AuthenticationFilter>;
};


export type QueryWebHostingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWebHostingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WebHostingFilter>;
};


export type QueryBaasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBaasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BaasFilter>;
};


export type QueryCloudProvidersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCloudProvidersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CloudProvidersFilter>;
};


export type QueryFrameworksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFrameworksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FrameworksFilter>;
};


export type QueryPaasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPaasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PaasFilter>;
};

export type DocumentFilter = {
  authentication?: InputMaybe<AuthenticationFilter>;
  webHosting?: InputMaybe<WebHostingFilter>;
  baas?: InputMaybe<BaasFilter>;
  cloudProviders?: InputMaybe<CloudProvidersFilter>;
  frameworks?: InputMaybe<FrameworksFilter>;
  paas?: InputMaybe<PaasFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Authentication | WebHosting | Baas | CloudProviders | Frameworks | Paas | Folder;

export type AuthenticationAdditionalInfoInfoListItem = {
  __typename?: 'AuthenticationAdditionalInfoInfoListItem';
  content?: Maybe<Scalars['String']['output']>;
};

export type AuthenticationAdditionalInfoInfoListWarning = {
  __typename?: 'AuthenticationAdditionalInfoInfoListWarning';
  content?: Maybe<Scalars['String']['output']>;
};

export type AuthenticationAdditionalInfo = AuthenticationAdditionalInfoInfoListItem | AuthenticationAdditionalInfoInfoListWarning;

export type Authentication = Node & Document & {
  __typename?: 'Authentication';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  descriptionOfFreePlan?: Maybe<Scalars['String']['output']>;
  siteLink: Scalars['String']['output'];
  additionalInfo?: Maybe<Array<Maybe<AuthenticationAdditionalInfo>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AuthenticationAdditionalInfoInfoListItemFilter = {
  content?: InputMaybe<StringFilter>;
};

export type AuthenticationAdditionalInfoInfoListWarningFilter = {
  content?: InputMaybe<StringFilter>;
};

export type AuthenticationAdditionalInfoFilter = {
  infoListItem?: InputMaybe<AuthenticationAdditionalInfoInfoListItemFilter>;
  infoListWarning?: InputMaybe<AuthenticationAdditionalInfoInfoListWarningFilter>;
};

export type AuthenticationFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  additionalInfo?: InputMaybe<AuthenticationAdditionalInfoFilter>;
};

export type AuthenticationConnectionEdges = {
  __typename?: 'AuthenticationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Authentication>;
};

export type AuthenticationConnection = Connection & {
  __typename?: 'AuthenticationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AuthenticationConnectionEdges>>>;
};

export type WebHostingAdditionalInfoInfoListItem = {
  __typename?: 'WebHostingAdditionalInfoInfoListItem';
  content?: Maybe<Scalars['String']['output']>;
};

export type WebHostingAdditionalInfoInfoListWarning = {
  __typename?: 'WebHostingAdditionalInfoInfoListWarning';
  content?: Maybe<Scalars['String']['output']>;
};

export type WebHostingAdditionalInfo = WebHostingAdditionalInfoInfoListItem | WebHostingAdditionalInfoInfoListWarning;

export type WebHosting = Node & Document & {
  __typename?: 'WebHosting';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  descriptionOfFreePlan?: Maybe<Scalars['String']['output']>;
  siteLink: Scalars['String']['output'];
  additionalInfo?: Maybe<Array<Maybe<WebHostingAdditionalInfo>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WebHostingAdditionalInfoInfoListItemFilter = {
  content?: InputMaybe<StringFilter>;
};

export type WebHostingAdditionalInfoInfoListWarningFilter = {
  content?: InputMaybe<StringFilter>;
};

export type WebHostingAdditionalInfoFilter = {
  infoListItem?: InputMaybe<WebHostingAdditionalInfoInfoListItemFilter>;
  infoListWarning?: InputMaybe<WebHostingAdditionalInfoInfoListWarningFilter>;
};

export type WebHostingFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  additionalInfo?: InputMaybe<WebHostingAdditionalInfoFilter>;
};

export type WebHostingConnectionEdges = {
  __typename?: 'WebHostingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<WebHosting>;
};

export type WebHostingConnection = Connection & {
  __typename?: 'WebHostingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WebHostingConnectionEdges>>>;
};

export type BaasAdditionalInfoInfoListItem = {
  __typename?: 'BaasAdditionalInfoInfoListItem';
  content?: Maybe<Scalars['String']['output']>;
};

export type BaasAdditionalInfoInfoListWarning = {
  __typename?: 'BaasAdditionalInfoInfoListWarning';
  content?: Maybe<Scalars['String']['output']>;
};

export type BaasAdditionalInfo = BaasAdditionalInfoInfoListItem | BaasAdditionalInfoInfoListWarning;

export type Baas = Node & Document & {
  __typename?: 'Baas';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  descriptionOfFreePlan?: Maybe<Scalars['String']['output']>;
  siteLink: Scalars['String']['output'];
  additionalInfo?: Maybe<Array<Maybe<BaasAdditionalInfo>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BaasAdditionalInfoInfoListItemFilter = {
  content?: InputMaybe<StringFilter>;
};

export type BaasAdditionalInfoInfoListWarningFilter = {
  content?: InputMaybe<StringFilter>;
};

export type BaasAdditionalInfoFilter = {
  infoListItem?: InputMaybe<BaasAdditionalInfoInfoListItemFilter>;
  infoListWarning?: InputMaybe<BaasAdditionalInfoInfoListWarningFilter>;
};

export type BaasFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  additionalInfo?: InputMaybe<BaasAdditionalInfoFilter>;
};

export type BaasConnectionEdges = {
  __typename?: 'BaasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Baas>;
};

export type BaasConnection = Connection & {
  __typename?: 'BaasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BaasConnectionEdges>>>;
};

export type CloudProvidersAdditionalInfoInfoListItem = {
  __typename?: 'CloudProvidersAdditionalInfoInfoListItem';
  content?: Maybe<Scalars['String']['output']>;
};

export type CloudProvidersAdditionalInfoInfoListWarning = {
  __typename?: 'CloudProvidersAdditionalInfoInfoListWarning';
  content?: Maybe<Scalars['String']['output']>;
};

export type CloudProvidersAdditionalInfo = CloudProvidersAdditionalInfoInfoListItem | CloudProvidersAdditionalInfoInfoListWarning;

export type CloudProviders = Node & Document & {
  __typename?: 'CloudProviders';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  descriptionOfFreePlan?: Maybe<Scalars['String']['output']>;
  siteLink: Scalars['String']['output'];
  additionalInfo?: Maybe<Array<Maybe<CloudProvidersAdditionalInfo>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CloudProvidersAdditionalInfoInfoListItemFilter = {
  content?: InputMaybe<StringFilter>;
};

export type CloudProvidersAdditionalInfoInfoListWarningFilter = {
  content?: InputMaybe<StringFilter>;
};

export type CloudProvidersAdditionalInfoFilter = {
  infoListItem?: InputMaybe<CloudProvidersAdditionalInfoInfoListItemFilter>;
  infoListWarning?: InputMaybe<CloudProvidersAdditionalInfoInfoListWarningFilter>;
};

export type CloudProvidersFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  additionalInfo?: InputMaybe<CloudProvidersAdditionalInfoFilter>;
};

export type CloudProvidersConnectionEdges = {
  __typename?: 'CloudProvidersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CloudProviders>;
};

export type CloudProvidersConnection = Connection & {
  __typename?: 'CloudProvidersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CloudProvidersConnectionEdges>>>;
};

export type FrameworksAdditionalInfoInfoListItem = {
  __typename?: 'FrameworksAdditionalInfoInfoListItem';
  content?: Maybe<Scalars['String']['output']>;
};

export type FrameworksAdditionalInfoInfoListWarning = {
  __typename?: 'FrameworksAdditionalInfoInfoListWarning';
  content?: Maybe<Scalars['String']['output']>;
};

export type FrameworksAdditionalInfo = FrameworksAdditionalInfoInfoListItem | FrameworksAdditionalInfoInfoListWarning;

export type Frameworks = Node & Document & {
  __typename?: 'Frameworks';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  siteLink: Scalars['String']['output'];
  additionalInfo?: Maybe<Array<Maybe<FrameworksAdditionalInfo>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FrameworksAdditionalInfoInfoListItemFilter = {
  content?: InputMaybe<StringFilter>;
};

export type FrameworksAdditionalInfoInfoListWarningFilter = {
  content?: InputMaybe<StringFilter>;
};

export type FrameworksAdditionalInfoFilter = {
  infoListItem?: InputMaybe<FrameworksAdditionalInfoInfoListItemFilter>;
  infoListWarning?: InputMaybe<FrameworksAdditionalInfoInfoListWarningFilter>;
};

export type FrameworksFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  additionalInfo?: InputMaybe<FrameworksAdditionalInfoFilter>;
};

export type FrameworksConnectionEdges = {
  __typename?: 'FrameworksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Frameworks>;
};

export type FrameworksConnection = Connection & {
  __typename?: 'FrameworksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FrameworksConnectionEdges>>>;
};

export type PaasAdditionalInfoInfoListItem = {
  __typename?: 'PaasAdditionalInfoInfoListItem';
  content?: Maybe<Scalars['String']['output']>;
};

export type PaasAdditionalInfoInfoListWarning = {
  __typename?: 'PaasAdditionalInfoInfoListWarning';
  content?: Maybe<Scalars['String']['output']>;
};

export type PaasAdditionalInfo = PaasAdditionalInfoInfoListItem | PaasAdditionalInfoInfoListWarning;

export type Paas = Node & Document & {
  __typename?: 'Paas';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  descriptionOfFreePlan?: Maybe<Scalars['String']['output']>;
  siteLink: Scalars['String']['output'];
  additionalInfo?: Maybe<Array<Maybe<PaasAdditionalInfo>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PaasAdditionalInfoInfoListItemFilter = {
  content?: InputMaybe<StringFilter>;
};

export type PaasAdditionalInfoInfoListWarningFilter = {
  content?: InputMaybe<StringFilter>;
};

export type PaasAdditionalInfoFilter = {
  infoListItem?: InputMaybe<PaasAdditionalInfoInfoListItemFilter>;
  infoListWarning?: InputMaybe<PaasAdditionalInfoInfoListWarningFilter>;
};

export type PaasFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  additionalInfo?: InputMaybe<PaasAdditionalInfoFilter>;
};

export type PaasConnectionEdges = {
  __typename?: 'PaasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Paas>;
};

export type PaasConnection = Connection & {
  __typename?: 'PaasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PaasConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateAuthentication: Authentication;
  createAuthentication: Authentication;
  updateWebHosting: WebHosting;
  createWebHosting: WebHosting;
  updateBaas: Baas;
  createBaas: Baas;
  updateCloudProviders: CloudProviders;
  createCloudProviders: CloudProviders;
  updateFrameworks: Frameworks;
  createFrameworks: Frameworks;
  updatePaas: Paas;
  createPaas: Paas;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdateAuthenticationArgs = {
  relativePath: Scalars['String']['input'];
  params: AuthenticationMutation;
};


export type MutationCreateAuthenticationArgs = {
  relativePath: Scalars['String']['input'];
  params: AuthenticationMutation;
};


export type MutationUpdateWebHostingArgs = {
  relativePath: Scalars['String']['input'];
  params: WebHostingMutation;
};


export type MutationCreateWebHostingArgs = {
  relativePath: Scalars['String']['input'];
  params: WebHostingMutation;
};


export type MutationUpdateBaasArgs = {
  relativePath: Scalars['String']['input'];
  params: BaasMutation;
};


export type MutationCreateBaasArgs = {
  relativePath: Scalars['String']['input'];
  params: BaasMutation;
};


export type MutationUpdateCloudProvidersArgs = {
  relativePath: Scalars['String']['input'];
  params: CloudProvidersMutation;
};


export type MutationCreateCloudProvidersArgs = {
  relativePath: Scalars['String']['input'];
  params: CloudProvidersMutation;
};


export type MutationUpdateFrameworksArgs = {
  relativePath: Scalars['String']['input'];
  params: FrameworksMutation;
};


export type MutationCreateFrameworksArgs = {
  relativePath: Scalars['String']['input'];
  params: FrameworksMutation;
};


export type MutationUpdatePaasArgs = {
  relativePath: Scalars['String']['input'];
  params: PaasMutation;
};


export type MutationCreatePaasArgs = {
  relativePath: Scalars['String']['input'];
  params: PaasMutation;
};

export type DocumentUpdateMutation = {
  authentication?: InputMaybe<AuthenticationMutation>;
  webHosting?: InputMaybe<WebHostingMutation>;
  baas?: InputMaybe<BaasMutation>;
  cloudProviders?: InputMaybe<CloudProvidersMutation>;
  frameworks?: InputMaybe<FrameworksMutation>;
  paas?: InputMaybe<PaasMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  authentication?: InputMaybe<AuthenticationMutation>;
  webHosting?: InputMaybe<WebHostingMutation>;
  baas?: InputMaybe<BaasMutation>;
  cloudProviders?: InputMaybe<CloudProvidersMutation>;
  frameworks?: InputMaybe<FrameworksMutation>;
  paas?: InputMaybe<PaasMutation>;
};

export type AuthenticationAdditionalInfoInfoListItemMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type AuthenticationAdditionalInfoInfoListWarningMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type AuthenticationAdditionalInfoMutation = {
  infoListItem?: InputMaybe<AuthenticationAdditionalInfoInfoListItemMutation>;
  infoListWarning?: InputMaybe<AuthenticationAdditionalInfoInfoListWarningMutation>;
};

export type AuthenticationMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']['input']>;
  siteLink?: InputMaybe<Scalars['String']['input']>;
  additionalInfo?: InputMaybe<Array<InputMaybe<AuthenticationAdditionalInfoMutation>>>;
};

export type WebHostingAdditionalInfoInfoListItemMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type WebHostingAdditionalInfoInfoListWarningMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type WebHostingAdditionalInfoMutation = {
  infoListItem?: InputMaybe<WebHostingAdditionalInfoInfoListItemMutation>;
  infoListWarning?: InputMaybe<WebHostingAdditionalInfoInfoListWarningMutation>;
};

export type WebHostingMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']['input']>;
  siteLink?: InputMaybe<Scalars['String']['input']>;
  additionalInfo?: InputMaybe<Array<InputMaybe<WebHostingAdditionalInfoMutation>>>;
};

export type BaasAdditionalInfoInfoListItemMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type BaasAdditionalInfoInfoListWarningMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type BaasAdditionalInfoMutation = {
  infoListItem?: InputMaybe<BaasAdditionalInfoInfoListItemMutation>;
  infoListWarning?: InputMaybe<BaasAdditionalInfoInfoListWarningMutation>;
};

export type BaasMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']['input']>;
  siteLink?: InputMaybe<Scalars['String']['input']>;
  additionalInfo?: InputMaybe<Array<InputMaybe<BaasAdditionalInfoMutation>>>;
};

export type CloudProvidersAdditionalInfoInfoListItemMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type CloudProvidersAdditionalInfoInfoListWarningMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type CloudProvidersAdditionalInfoMutation = {
  infoListItem?: InputMaybe<CloudProvidersAdditionalInfoInfoListItemMutation>;
  infoListWarning?: InputMaybe<CloudProvidersAdditionalInfoInfoListWarningMutation>;
};

export type CloudProvidersMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']['input']>;
  siteLink?: InputMaybe<Scalars['String']['input']>;
  additionalInfo?: InputMaybe<Array<InputMaybe<CloudProvidersAdditionalInfoMutation>>>;
};

export type FrameworksAdditionalInfoInfoListItemMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type FrameworksAdditionalInfoInfoListWarningMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type FrameworksAdditionalInfoMutation = {
  infoListItem?: InputMaybe<FrameworksAdditionalInfoInfoListItemMutation>;
  infoListWarning?: InputMaybe<FrameworksAdditionalInfoInfoListWarningMutation>;
};

export type FrameworksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  siteLink?: InputMaybe<Scalars['String']['input']>;
  additionalInfo?: InputMaybe<Array<InputMaybe<FrameworksAdditionalInfoMutation>>>;
};

export type PaasAdditionalInfoInfoListItemMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type PaasAdditionalInfoInfoListWarningMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type PaasAdditionalInfoMutation = {
  infoListItem?: InputMaybe<PaasAdditionalInfoInfoListItemMutation>;
  infoListWarning?: InputMaybe<PaasAdditionalInfoInfoListWarningMutation>;
};

export type PaasMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']['input']>;
  siteLink?: InputMaybe<Scalars['String']['input']>;
  additionalInfo?: InputMaybe<Array<InputMaybe<PaasAdditionalInfoMutation>>>;
};

export type AuthenticationPartsFragment = { __typename?: 'Authentication', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, additionalInfo?: Array<{ __typename: 'AuthenticationAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'AuthenticationAdditionalInfoInfoListWarning', content?: string | null } | null> | null };

export type WebHostingPartsFragment = { __typename?: 'WebHosting', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, additionalInfo?: Array<{ __typename: 'WebHostingAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'WebHostingAdditionalInfoInfoListWarning', content?: string | null } | null> | null };

export type BaasPartsFragment = { __typename?: 'Baas', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, additionalInfo?: Array<{ __typename: 'BaasAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'BaasAdditionalInfoInfoListWarning', content?: string | null } | null> | null };

export type CloudProvidersPartsFragment = { __typename?: 'CloudProviders', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, additionalInfo?: Array<{ __typename: 'CloudProvidersAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'CloudProvidersAdditionalInfoInfoListWarning', content?: string | null } | null> | null };

export type FrameworksPartsFragment = { __typename?: 'Frameworks', title: string, description: string, siteLink: string, additionalInfo?: Array<{ __typename: 'FrameworksAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'FrameworksAdditionalInfoInfoListWarning', content?: string | null } | null> | null };

export type PaasPartsFragment = { __typename?: 'Paas', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, additionalInfo?: Array<{ __typename: 'PaasAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'PaasAdditionalInfoInfoListWarning', content?: string | null } | null> | null };

export type AuthenticationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AuthenticationQuery = { __typename?: 'Query', authentication: { __typename?: 'Authentication', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'AuthenticationAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'AuthenticationAdditionalInfoInfoListWarning', content?: string | null } | null> | null } };

export type AuthenticationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AuthenticationFilter>;
}>;


export type AuthenticationConnectionQuery = { __typename?: 'Query', authenticationConnection: { __typename?: 'AuthenticationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AuthenticationConnectionEdges', cursor: string, node?: { __typename?: 'Authentication', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'AuthenticationAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'AuthenticationAdditionalInfoInfoListWarning', content?: string | null } | null> | null } | null } | null> | null } };

export type WebHostingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WebHostingQuery = { __typename?: 'Query', webHosting: { __typename?: 'WebHosting', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'WebHostingAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'WebHostingAdditionalInfoInfoListWarning', content?: string | null } | null> | null } };

export type WebHostingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WebHostingFilter>;
}>;


export type WebHostingConnectionQuery = { __typename?: 'Query', webHostingConnection: { __typename?: 'WebHostingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WebHostingConnectionEdges', cursor: string, node?: { __typename?: 'WebHosting', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'WebHostingAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'WebHostingAdditionalInfoInfoListWarning', content?: string | null } | null> | null } | null } | null> | null } };

export type BaasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BaasQuery = { __typename?: 'Query', baas: { __typename?: 'Baas', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'BaasAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'BaasAdditionalInfoInfoListWarning', content?: string | null } | null> | null } };

export type BaasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BaasFilter>;
}>;


export type BaasConnectionQuery = { __typename?: 'Query', baasConnection: { __typename?: 'BaasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BaasConnectionEdges', cursor: string, node?: { __typename?: 'Baas', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'BaasAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'BaasAdditionalInfoInfoListWarning', content?: string | null } | null> | null } | null } | null> | null } };

export type CloudProvidersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CloudProvidersQuery = { __typename?: 'Query', cloudProviders: { __typename?: 'CloudProviders', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'CloudProvidersAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'CloudProvidersAdditionalInfoInfoListWarning', content?: string | null } | null> | null } };

export type CloudProvidersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CloudProvidersFilter>;
}>;


export type CloudProvidersConnectionQuery = { __typename?: 'Query', cloudProvidersConnection: { __typename?: 'CloudProvidersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CloudProvidersConnectionEdges', cursor: string, node?: { __typename?: 'CloudProviders', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'CloudProvidersAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'CloudProvidersAdditionalInfoInfoListWarning', content?: string | null } | null> | null } | null } | null> | null } };

export type FrameworksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FrameworksQuery = { __typename?: 'Query', frameworks: { __typename?: 'Frameworks', id: string, title: string, description: string, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'FrameworksAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'FrameworksAdditionalInfoInfoListWarning', content?: string | null } | null> | null } };

export type FrameworksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FrameworksFilter>;
}>;


export type FrameworksConnectionQuery = { __typename?: 'Query', frameworksConnection: { __typename?: 'FrameworksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FrameworksConnectionEdges', cursor: string, node?: { __typename?: 'Frameworks', id: string, title: string, description: string, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'FrameworksAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'FrameworksAdditionalInfoInfoListWarning', content?: string | null } | null> | null } | null } | null> | null } };

export type PaasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PaasQuery = { __typename?: 'Query', paas: { __typename?: 'Paas', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'PaasAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'PaasAdditionalInfoInfoListWarning', content?: string | null } | null> | null } };

export type PaasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PaasFilter>;
}>;


export type PaasConnectionQuery = { __typename?: 'Query', paasConnection: { __typename?: 'PaasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PaasConnectionEdges', cursor: string, node?: { __typename?: 'Paas', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, additionalInfo?: Array<{ __typename: 'PaasAdditionalInfoInfoListItem', content?: string | null } | { __typename: 'PaasAdditionalInfoInfoListWarning', content?: string | null } | null> | null } | null } | null> | null } };

export const AuthenticationPartsFragmentDoc = gql`
    fragment AuthenticationParts on Authentication {
  title
  description
  descriptionOfFreePlan
  siteLink
  additionalInfo {
    __typename
    ... on AuthenticationAdditionalInfoInfoListItem {
      content
    }
    ... on AuthenticationAdditionalInfoInfoListWarning {
      content
    }
  }
}
    `;
export const WebHostingPartsFragmentDoc = gql`
    fragment WebHostingParts on WebHosting {
  title
  description
  descriptionOfFreePlan
  siteLink
  additionalInfo {
    __typename
    ... on WebHostingAdditionalInfoInfoListItem {
      content
    }
    ... on WebHostingAdditionalInfoInfoListWarning {
      content
    }
  }
}
    `;
export const BaasPartsFragmentDoc = gql`
    fragment BaasParts on Baas {
  title
  description
  descriptionOfFreePlan
  siteLink
  additionalInfo {
    __typename
    ... on BaasAdditionalInfoInfoListItem {
      content
    }
    ... on BaasAdditionalInfoInfoListWarning {
      content
    }
  }
}
    `;
export const CloudProvidersPartsFragmentDoc = gql`
    fragment CloudProvidersParts on CloudProviders {
  title
  description
  descriptionOfFreePlan
  siteLink
  additionalInfo {
    __typename
    ... on CloudProvidersAdditionalInfoInfoListItem {
      content
    }
    ... on CloudProvidersAdditionalInfoInfoListWarning {
      content
    }
  }
}
    `;
export const FrameworksPartsFragmentDoc = gql`
    fragment FrameworksParts on Frameworks {
  title
  description
  siteLink
  additionalInfo {
    __typename
    ... on FrameworksAdditionalInfoInfoListItem {
      content
    }
    ... on FrameworksAdditionalInfoInfoListWarning {
      content
    }
  }
}
    `;
export const PaasPartsFragmentDoc = gql`
    fragment PaasParts on Paas {
  title
  description
  descriptionOfFreePlan
  siteLink
  additionalInfo {
    __typename
    ... on PaasAdditionalInfoInfoListItem {
      content
    }
    ... on PaasAdditionalInfoInfoListWarning {
      content
    }
  }
}
    `;
export const AuthenticationDocument = gql`
    query authentication($relativePath: String!) {
  authentication(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AuthenticationParts
  }
}
    ${AuthenticationPartsFragmentDoc}`;
export const AuthenticationConnectionDocument = gql`
    query authenticationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AuthenticationFilter) {
  authenticationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AuthenticationParts
      }
    }
  }
}
    ${AuthenticationPartsFragmentDoc}`;
export const WebHostingDocument = gql`
    query webHosting($relativePath: String!) {
  webHosting(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WebHostingParts
  }
}
    ${WebHostingPartsFragmentDoc}`;
export const WebHostingConnectionDocument = gql`
    query webHostingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WebHostingFilter) {
  webHostingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WebHostingParts
      }
    }
  }
}
    ${WebHostingPartsFragmentDoc}`;
export const BaasDocument = gql`
    query baas($relativePath: String!) {
  baas(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BaasParts
  }
}
    ${BaasPartsFragmentDoc}`;
export const BaasConnectionDocument = gql`
    query baasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BaasFilter) {
  baasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BaasParts
      }
    }
  }
}
    ${BaasPartsFragmentDoc}`;
export const CloudProvidersDocument = gql`
    query cloudProviders($relativePath: String!) {
  cloudProviders(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CloudProvidersParts
  }
}
    ${CloudProvidersPartsFragmentDoc}`;
export const CloudProvidersConnectionDocument = gql`
    query cloudProvidersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CloudProvidersFilter) {
  cloudProvidersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CloudProvidersParts
      }
    }
  }
}
    ${CloudProvidersPartsFragmentDoc}`;
export const FrameworksDocument = gql`
    query frameworks($relativePath: String!) {
  frameworks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FrameworksParts
  }
}
    ${FrameworksPartsFragmentDoc}`;
export const FrameworksConnectionDocument = gql`
    query frameworksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FrameworksFilter) {
  frameworksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FrameworksParts
      }
    }
  }
}
    ${FrameworksPartsFragmentDoc}`;
export const PaasDocument = gql`
    query paas($relativePath: String!) {
  paas(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PaasParts
  }
}
    ${PaasPartsFragmentDoc}`;
export const PaasConnectionDocument = gql`
    query paasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PaasFilter) {
  paasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PaasParts
      }
    }
  }
}
    ${PaasPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      authentication(variables: AuthenticationQueryVariables, options?: C): Promise<{data: AuthenticationQuery, variables: AuthenticationQueryVariables, query: string}> {
        return requester<{data: AuthenticationQuery, variables: AuthenticationQueryVariables, query: string}, AuthenticationQueryVariables>(AuthenticationDocument, variables, options);
      },
    authenticationConnection(variables?: AuthenticationConnectionQueryVariables, options?: C): Promise<{data: AuthenticationConnectionQuery, variables: AuthenticationConnectionQueryVariables, query: string}> {
        return requester<{data: AuthenticationConnectionQuery, variables: AuthenticationConnectionQueryVariables, query: string}, AuthenticationConnectionQueryVariables>(AuthenticationConnectionDocument, variables, options);
      },
    webHosting(variables: WebHostingQueryVariables, options?: C): Promise<{data: WebHostingQuery, variables: WebHostingQueryVariables, query: string}> {
        return requester<{data: WebHostingQuery, variables: WebHostingQueryVariables, query: string}, WebHostingQueryVariables>(WebHostingDocument, variables, options);
      },
    webHostingConnection(variables?: WebHostingConnectionQueryVariables, options?: C): Promise<{data: WebHostingConnectionQuery, variables: WebHostingConnectionQueryVariables, query: string}> {
        return requester<{data: WebHostingConnectionQuery, variables: WebHostingConnectionQueryVariables, query: string}, WebHostingConnectionQueryVariables>(WebHostingConnectionDocument, variables, options);
      },
    baas(variables: BaasQueryVariables, options?: C): Promise<{data: BaasQuery, variables: BaasQueryVariables, query: string}> {
        return requester<{data: BaasQuery, variables: BaasQueryVariables, query: string}, BaasQueryVariables>(BaasDocument, variables, options);
      },
    baasConnection(variables?: BaasConnectionQueryVariables, options?: C): Promise<{data: BaasConnectionQuery, variables: BaasConnectionQueryVariables, query: string}> {
        return requester<{data: BaasConnectionQuery, variables: BaasConnectionQueryVariables, query: string}, BaasConnectionQueryVariables>(BaasConnectionDocument, variables, options);
      },
    cloudProviders(variables: CloudProvidersQueryVariables, options?: C): Promise<{data: CloudProvidersQuery, variables: CloudProvidersQueryVariables, query: string}> {
        return requester<{data: CloudProvidersQuery, variables: CloudProvidersQueryVariables, query: string}, CloudProvidersQueryVariables>(CloudProvidersDocument, variables, options);
      },
    cloudProvidersConnection(variables?: CloudProvidersConnectionQueryVariables, options?: C): Promise<{data: CloudProvidersConnectionQuery, variables: CloudProvidersConnectionQueryVariables, query: string}> {
        return requester<{data: CloudProvidersConnectionQuery, variables: CloudProvidersConnectionQueryVariables, query: string}, CloudProvidersConnectionQueryVariables>(CloudProvidersConnectionDocument, variables, options);
      },
    frameworks(variables: FrameworksQueryVariables, options?: C): Promise<{data: FrameworksQuery, variables: FrameworksQueryVariables, query: string}> {
        return requester<{data: FrameworksQuery, variables: FrameworksQueryVariables, query: string}, FrameworksQueryVariables>(FrameworksDocument, variables, options);
      },
    frameworksConnection(variables?: FrameworksConnectionQueryVariables, options?: C): Promise<{data: FrameworksConnectionQuery, variables: FrameworksConnectionQueryVariables, query: string}> {
        return requester<{data: FrameworksConnectionQuery, variables: FrameworksConnectionQueryVariables, query: string}, FrameworksConnectionQueryVariables>(FrameworksConnectionDocument, variables, options);
      },
    paas(variables: PaasQueryVariables, options?: C): Promise<{data: PaasQuery, variables: PaasQueryVariables, query: string}> {
        return requester<{data: PaasQuery, variables: PaasQueryVariables, query: string}, PaasQueryVariables>(PaasDocument, variables, options);
      },
    paasConnection(variables?: PaasConnectionQueryVariables, options?: C): Promise<{data: PaasConnectionQuery, variables: PaasConnectionQueryVariables, query: string}> {
        return requester<{data: PaasConnectionQuery, variables: PaasConnectionQueryVariables, query: string}, PaasConnectionQueryVariables>(PaasConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.4/content/15b91600-bcf8-49f2-8652-baab6358e974/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
  options?: {
    branch?: string
  }
) => {
  const requester = generateRequester(client, options)
  return getSdk(requester)
}

  