fragment AuthenticationParts on Authentication {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
  comparisonInfo {
    __typename
    monthlyActiveUsers
    emailAndPasswordAuth
    magicLinks
    socialLogins
    phoneNumberAuth
    anonymousAuthentication
    multiFactorAuthentication
    userInterfaceProvided
    customDomain
    noBrandWatermark
  }
}

fragment WebHostingParts on WebHosting {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
  comparisonInfo {
    __typename
    siteLimit
    freeBandwidth
    additionalBandwidthCost
    freeBuildMinutes
    concurrentBuilds
    deploymentPreview
    serverlessFunctionExecution
    serverlessFunctionInvocations
    serverlessFunctionExecutionTimeout
    edgeFunctionExecution
    globalCdn
    customHeaders
    https
    ddosProtection
  }
}

fragment DatabasesParts on Databases {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}

fragment BaasParts on Baas {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}

fragment CloudProvidersParts on CloudProviders {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}

fragment FrameworksParts on Frameworks {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}

fragment SecurityParts on Security {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}

fragment ImagesParts on Images {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}

fragment AnalyticsParts on Analytics {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
