//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  authentication: Authentication;
  authenticationConnection: AuthenticationConnection;
  webHosting: WebHosting;
  webHostingConnection: WebHostingConnection;
  databases: Databases;
  databasesConnection: DatabasesConnection;
  baas: Baas;
  baasConnection: BaasConnection;
  cloudProviders: CloudProviders;
  cloudProvidersConnection: CloudProvidersConnection;
  frameworks: Frameworks;
  frameworksConnection: FrameworksConnection;
  security: Security;
  securityConnection: SecurityConnection;
  images: Images;
  imagesConnection: ImagesConnection;
  analytics: Analytics;
  analyticsConnection: AnalyticsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryAuthenticationArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryAuthenticationConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<AuthenticationFilter>;
};


export type QueryWebHostingArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryWebHostingConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<WebHostingFilter>;
};


export type QueryDatabasesArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryDatabasesConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DatabasesFilter>;
};


export type QueryBaasArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryBaasConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<BaasFilter>;
};


export type QueryCloudProvidersArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryCloudProvidersConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<CloudProvidersFilter>;
};


export type QueryFrameworksArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryFrameworksConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<FrameworksFilter>;
};


export type QuerySecurityArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QuerySecurityConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<SecurityFilter>;
};


export type QueryImagesArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryImagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<ImagesFilter>;
};


export type QueryAnalyticsArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryAnalyticsConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<AnalyticsFilter>;
};

export type DocumentFilter = {
  authentication?: InputMaybe<AuthenticationFilter>;
  webHosting?: InputMaybe<WebHostingFilter>;
  databases?: InputMaybe<DatabasesFilter>;
  baas?: InputMaybe<BaasFilter>;
  cloudProviders?: InputMaybe<CloudProvidersFilter>;
  frameworks?: InputMaybe<FrameworksFilter>;
  security?: InputMaybe<SecurityFilter>;
  images?: InputMaybe<ImagesFilter>;
  analytics?: InputMaybe<AnalyticsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DocumentFilter>;
};

export type DocumentNode = Authentication | WebHosting | Databases | Baas | CloudProviders | Frameworks | Security | Images | Analytics;

export type AuthenticationAddOnThumbnail = {
  __typename?: 'AuthenticationAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type AuthenticationGithubInfo = {
  __typename?: 'AuthenticationGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type AuthenticationComparisonInfo = {
  __typename?: 'AuthenticationComparisonInfo';
  monthlyActiveUsers?: Maybe<Scalars['String']>;
  emailAndPasswordAuth?: Maybe<Scalars['Boolean']>;
  magicLinks?: Maybe<Scalars['Boolean']>;
  socialLogins?: Maybe<Scalars['String']>;
  phoneNumberAuth?: Maybe<Scalars['String']>;
  anonymousAuthentication?: Maybe<Scalars['Boolean']>;
  multiFactorAuthentication?: Maybe<Scalars['Boolean']>;
  userInterfaceProvided?: Maybe<Scalars['Boolean']>;
  customDomain?: Maybe<Scalars['Boolean']>;
  noBrandWatermark?: Maybe<Scalars['Boolean']>;
};

export type Authentication = Node & Document & {
  __typename?: 'Authentication';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<AuthenticationAddOnThumbnail>;
  githubInfo?: Maybe<AuthenticationGithubInfo>;
  comparisonInfo?: Maybe<AuthenticationComparisonInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type AuthenticationAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type AuthenticationGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type AuthenticationComparisonInfoFilter = {
  monthlyActiveUsers?: InputMaybe<StringFilter>;
  emailAndPasswordAuth?: InputMaybe<BooleanFilter>;
  magicLinks?: InputMaybe<BooleanFilter>;
  socialLogins?: InputMaybe<StringFilter>;
  phoneNumberAuth?: InputMaybe<StringFilter>;
  anonymousAuthentication?: InputMaybe<BooleanFilter>;
  multiFactorAuthentication?: InputMaybe<BooleanFilter>;
  userInterfaceProvided?: InputMaybe<BooleanFilter>;
  customDomain?: InputMaybe<BooleanFilter>;
  noBrandWatermark?: InputMaybe<BooleanFilter>;
};

export type AuthenticationFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<AuthenticationAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<AuthenticationGithubInfoFilter>;
  comparisonInfo?: InputMaybe<AuthenticationComparisonInfoFilter>;
};

export type AuthenticationConnectionEdges = {
  __typename?: 'AuthenticationConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Authentication>;
};

export type AuthenticationConnection = Connection & {
  __typename?: 'AuthenticationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<AuthenticationConnectionEdges>>>;
};

export type WebHostingAddOnThumbnail = {
  __typename?: 'WebHostingAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type WebHostingGithubInfo = {
  __typename?: 'WebHostingGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type WebHostingComparisonInfo = {
  __typename?: 'WebHostingComparisonInfo';
  siteLimit?: Maybe<Scalars['String']>;
  freeBandwidth?: Maybe<Scalars['String']>;
  additionalBandwidthCost?: Maybe<Scalars['String']>;
  freeBuildMinutes?: Maybe<Scalars['String']>;
  concurrentBuilds?: Maybe<Scalars['String']>;
  deploymentPreview?: Maybe<Scalars['Boolean']>;
  serverlessFunctionExecution?: Maybe<Scalars['String']>;
  serverlessFunctionInvocations?: Maybe<Scalars['String']>;
  serverlessFunctionExecutionTimeout?: Maybe<Scalars['String']>;
  edgeFunctionExecution?: Maybe<Scalars['String']>;
  globalCdn?: Maybe<Scalars['Boolean']>;
  customHeaders?: Maybe<Scalars['Boolean']>;
  https?: Maybe<Scalars['Boolean']>;
  ddosProtection?: Maybe<Scalars['Boolean']>;
};

export type WebHosting = Node & Document & {
  __typename?: 'WebHosting';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<WebHostingAddOnThumbnail>;
  githubInfo?: Maybe<WebHostingGithubInfo>;
  comparisonInfo?: Maybe<WebHostingComparisonInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type WebHostingAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type WebHostingGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type WebHostingComparisonInfoFilter = {
  siteLimit?: InputMaybe<StringFilter>;
  freeBandwidth?: InputMaybe<StringFilter>;
  additionalBandwidthCost?: InputMaybe<StringFilter>;
  freeBuildMinutes?: InputMaybe<StringFilter>;
  concurrentBuilds?: InputMaybe<StringFilter>;
  deploymentPreview?: InputMaybe<BooleanFilter>;
  serverlessFunctionExecution?: InputMaybe<StringFilter>;
  serverlessFunctionInvocations?: InputMaybe<StringFilter>;
  serverlessFunctionExecutionTimeout?: InputMaybe<StringFilter>;
  edgeFunctionExecution?: InputMaybe<StringFilter>;
  globalCdn?: InputMaybe<BooleanFilter>;
  customHeaders?: InputMaybe<BooleanFilter>;
  https?: InputMaybe<BooleanFilter>;
  ddosProtection?: InputMaybe<BooleanFilter>;
};

export type WebHostingFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<WebHostingAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<WebHostingGithubInfoFilter>;
  comparisonInfo?: InputMaybe<WebHostingComparisonInfoFilter>;
};

export type WebHostingConnectionEdges = {
  __typename?: 'WebHostingConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<WebHosting>;
};

export type WebHostingConnection = Connection & {
  __typename?: 'WebHostingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<WebHostingConnectionEdges>>>;
};

export type DatabasesAddOnThumbnail = {
  __typename?: 'DatabasesAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type DatabasesGithubInfo = {
  __typename?: 'DatabasesGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type Databases = Node & Document & {
  __typename?: 'Databases';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<DatabasesAddOnThumbnail>;
  githubInfo?: Maybe<DatabasesGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type DatabasesAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type DatabasesGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type DatabasesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<DatabasesAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<DatabasesGithubInfoFilter>;
};

export type DatabasesConnectionEdges = {
  __typename?: 'DatabasesConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Databases>;
};

export type DatabasesConnection = Connection & {
  __typename?: 'DatabasesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DatabasesConnectionEdges>>>;
};

export type BaasAddOnThumbnail = {
  __typename?: 'BaasAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type BaasGithubInfo = {
  __typename?: 'BaasGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type Baas = Node & Document & {
  __typename?: 'Baas';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<BaasAddOnThumbnail>;
  githubInfo?: Maybe<BaasGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type BaasAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type BaasGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type BaasFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<BaasAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<BaasGithubInfoFilter>;
};

export type BaasConnectionEdges = {
  __typename?: 'BaasConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Baas>;
};

export type BaasConnection = Connection & {
  __typename?: 'BaasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<BaasConnectionEdges>>>;
};

export type CloudProvidersAddOnThumbnail = {
  __typename?: 'CloudProvidersAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type CloudProvidersGithubInfo = {
  __typename?: 'CloudProvidersGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type CloudProviders = Node & Document & {
  __typename?: 'CloudProviders';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<CloudProvidersAddOnThumbnail>;
  githubInfo?: Maybe<CloudProvidersGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type CloudProvidersAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type CloudProvidersGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type CloudProvidersFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<CloudProvidersAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<CloudProvidersGithubInfoFilter>;
};

export type CloudProvidersConnectionEdges = {
  __typename?: 'CloudProvidersConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<CloudProviders>;
};

export type CloudProvidersConnection = Connection & {
  __typename?: 'CloudProvidersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<CloudProvidersConnectionEdges>>>;
};

export type FrameworksAddOnThumbnail = {
  __typename?: 'FrameworksAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type FrameworksGithubInfo = {
  __typename?: 'FrameworksGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type Frameworks = Node & Document & {
  __typename?: 'Frameworks';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<FrameworksAddOnThumbnail>;
  githubInfo?: Maybe<FrameworksGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type FrameworksAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type FrameworksGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type FrameworksFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<FrameworksAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<FrameworksGithubInfoFilter>;
};

export type FrameworksConnectionEdges = {
  __typename?: 'FrameworksConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Frameworks>;
};

export type FrameworksConnection = Connection & {
  __typename?: 'FrameworksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<FrameworksConnectionEdges>>>;
};

export type SecurityAddOnThumbnail = {
  __typename?: 'SecurityAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type SecurityGithubInfo = {
  __typename?: 'SecurityGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type Security = Node & Document & {
  __typename?: 'Security';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<SecurityAddOnThumbnail>;
  githubInfo?: Maybe<SecurityGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type SecurityAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type SecurityGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type SecurityFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<SecurityAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<SecurityGithubInfoFilter>;
};

export type SecurityConnectionEdges = {
  __typename?: 'SecurityConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Security>;
};

export type SecurityConnection = Connection & {
  __typename?: 'SecurityConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<SecurityConnectionEdges>>>;
};

export type ImagesAddOnThumbnail = {
  __typename?: 'ImagesAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type ImagesGithubInfo = {
  __typename?: 'ImagesGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type Images = Node & Document & {
  __typename?: 'Images';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<ImagesAddOnThumbnail>;
  githubInfo?: Maybe<ImagesGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type ImagesAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ImagesGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type ImagesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<ImagesAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<ImagesGithubInfoFilter>;
};

export type ImagesConnectionEdges = {
  __typename?: 'ImagesConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Images>;
};

export type ImagesConnection = Connection & {
  __typename?: 'ImagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<ImagesConnectionEdges>>>;
};

export type AnalyticsAddOnThumbnail = {
  __typename?: 'AnalyticsAddOnThumbnail';
  title?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type AnalyticsGithubInfo = {
  __typename?: 'AnalyticsGithubInfo';
  githubLink?: Maybe<Scalars['String']>;
  githubStars?: Maybe<Scalars['String']>;
};

export type Analytics = Node & Document & {
  __typename?: 'Analytics';
  title: Scalars['String'];
  description: Scalars['String'];
  descriptionOfFreePlan?: Maybe<Scalars['String']>;
  siteLink: Scalars['String'];
  pricingPage?: Maybe<Scalars['String']>;
  thumbnail: Scalars['String'];
  addOnThumbnail?: Maybe<AnalyticsAddOnThumbnail>;
  githubInfo?: Maybe<AnalyticsGithubInfo>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type AnalyticsAddOnThumbnailFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type AnalyticsGithubInfoFilter = {
  githubLink?: InputMaybe<StringFilter>;
  githubStars?: InputMaybe<StringFilter>;
};

export type AnalyticsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  descriptionOfFreePlan?: InputMaybe<StringFilter>;
  siteLink?: InputMaybe<StringFilter>;
  pricingPage?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  addOnThumbnail?: InputMaybe<AnalyticsAddOnThumbnailFilter>;
  githubInfo?: InputMaybe<AnalyticsGithubInfoFilter>;
};

export type AnalyticsConnectionEdges = {
  __typename?: 'AnalyticsConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Analytics>;
};

export type AnalyticsConnection = Connection & {
  __typename?: 'AnalyticsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<AnalyticsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateAuthentication: Authentication;
  createAuthentication: Authentication;
  updateWebHosting: WebHosting;
  createWebHosting: WebHosting;
  updateDatabases: Databases;
  createDatabases: Databases;
  updateBaas: Baas;
  createBaas: Baas;
  updateCloudProviders: CloudProviders;
  createCloudProviders: CloudProviders;
  updateFrameworks: Frameworks;
  createFrameworks: Frameworks;
  updateSecurity: Security;
  createSecurity: Security;
  updateImages: Images;
  createImages: Images;
  updateAnalytics: Analytics;
  createAnalytics: Analytics;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateAuthenticationArgs = {
  relativePath: Scalars['String'];
  params: AuthenticationMutation;
};


export type MutationCreateAuthenticationArgs = {
  relativePath: Scalars['String'];
  params: AuthenticationMutation;
};


export type MutationUpdateWebHostingArgs = {
  relativePath: Scalars['String'];
  params: WebHostingMutation;
};


export type MutationCreateWebHostingArgs = {
  relativePath: Scalars['String'];
  params: WebHostingMutation;
};


export type MutationUpdateDatabasesArgs = {
  relativePath: Scalars['String'];
  params: DatabasesMutation;
};


export type MutationCreateDatabasesArgs = {
  relativePath: Scalars['String'];
  params: DatabasesMutation;
};


export type MutationUpdateBaasArgs = {
  relativePath: Scalars['String'];
  params: BaasMutation;
};


export type MutationCreateBaasArgs = {
  relativePath: Scalars['String'];
  params: BaasMutation;
};


export type MutationUpdateCloudProvidersArgs = {
  relativePath: Scalars['String'];
  params: CloudProvidersMutation;
};


export type MutationCreateCloudProvidersArgs = {
  relativePath: Scalars['String'];
  params: CloudProvidersMutation;
};


export type MutationUpdateFrameworksArgs = {
  relativePath: Scalars['String'];
  params: FrameworksMutation;
};


export type MutationCreateFrameworksArgs = {
  relativePath: Scalars['String'];
  params: FrameworksMutation;
};


export type MutationUpdateSecurityArgs = {
  relativePath: Scalars['String'];
  params: SecurityMutation;
};


export type MutationCreateSecurityArgs = {
  relativePath: Scalars['String'];
  params: SecurityMutation;
};


export type MutationUpdateImagesArgs = {
  relativePath: Scalars['String'];
  params: ImagesMutation;
};


export type MutationCreateImagesArgs = {
  relativePath: Scalars['String'];
  params: ImagesMutation;
};


export type MutationUpdateAnalyticsArgs = {
  relativePath: Scalars['String'];
  params: AnalyticsMutation;
};


export type MutationCreateAnalyticsArgs = {
  relativePath: Scalars['String'];
  params: AnalyticsMutation;
};

export type DocumentUpdateMutation = {
  authentication?: InputMaybe<AuthenticationMutation>;
  webHosting?: InputMaybe<WebHostingMutation>;
  databases?: InputMaybe<DatabasesMutation>;
  baas?: InputMaybe<BaasMutation>;
  cloudProviders?: InputMaybe<CloudProvidersMutation>;
  frameworks?: InputMaybe<FrameworksMutation>;
  security?: InputMaybe<SecurityMutation>;
  images?: InputMaybe<ImagesMutation>;
  analytics?: InputMaybe<AnalyticsMutation>;
  relativePath?: InputMaybe<Scalars['String']>;
};

export type DocumentMutation = {
  authentication?: InputMaybe<AuthenticationMutation>;
  webHosting?: InputMaybe<WebHostingMutation>;
  databases?: InputMaybe<DatabasesMutation>;
  baas?: InputMaybe<BaasMutation>;
  cloudProviders?: InputMaybe<CloudProvidersMutation>;
  frameworks?: InputMaybe<FrameworksMutation>;
  security?: InputMaybe<SecurityMutation>;
  images?: InputMaybe<ImagesMutation>;
  analytics?: InputMaybe<AnalyticsMutation>;
};

export type AuthenticationAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type AuthenticationGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type AuthenticationComparisonInfoMutation = {
  monthlyActiveUsers?: InputMaybe<Scalars['String']>;
  emailAndPasswordAuth?: InputMaybe<Scalars['Boolean']>;
  magicLinks?: InputMaybe<Scalars['Boolean']>;
  socialLogins?: InputMaybe<Scalars['String']>;
  phoneNumberAuth?: InputMaybe<Scalars['String']>;
  anonymousAuthentication?: InputMaybe<Scalars['Boolean']>;
  multiFactorAuthentication?: InputMaybe<Scalars['Boolean']>;
  userInterfaceProvided?: InputMaybe<Scalars['Boolean']>;
  customDomain?: InputMaybe<Scalars['Boolean']>;
  noBrandWatermark?: InputMaybe<Scalars['Boolean']>;
};

export type AuthenticationMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<AuthenticationAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<AuthenticationGithubInfoMutation>;
  comparisonInfo?: InputMaybe<AuthenticationComparisonInfoMutation>;
};

export type WebHostingAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type WebHostingGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type WebHostingComparisonInfoMutation = {
  siteLimit?: InputMaybe<Scalars['String']>;
  freeBandwidth?: InputMaybe<Scalars['String']>;
  additionalBandwidthCost?: InputMaybe<Scalars['String']>;
  freeBuildMinutes?: InputMaybe<Scalars['String']>;
  concurrentBuilds?: InputMaybe<Scalars['String']>;
  deploymentPreview?: InputMaybe<Scalars['Boolean']>;
  serverlessFunctionExecution?: InputMaybe<Scalars['String']>;
  serverlessFunctionInvocations?: InputMaybe<Scalars['String']>;
  serverlessFunctionExecutionTimeout?: InputMaybe<Scalars['String']>;
  edgeFunctionExecution?: InputMaybe<Scalars['String']>;
  globalCdn?: InputMaybe<Scalars['Boolean']>;
  customHeaders?: InputMaybe<Scalars['Boolean']>;
  https?: InputMaybe<Scalars['Boolean']>;
  ddosProtection?: InputMaybe<Scalars['Boolean']>;
};

export type WebHostingMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<WebHostingAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<WebHostingGithubInfoMutation>;
  comparisonInfo?: InputMaybe<WebHostingComparisonInfoMutation>;
};

export type DatabasesAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type DatabasesGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type DatabasesMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<DatabasesAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<DatabasesGithubInfoMutation>;
};

export type BaasAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type BaasGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type BaasMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<BaasAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<BaasGithubInfoMutation>;
};

export type CloudProvidersAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type CloudProvidersGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type CloudProvidersMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<CloudProvidersAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<CloudProvidersGithubInfoMutation>;
};

export type FrameworksAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type FrameworksGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type FrameworksMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<FrameworksAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<FrameworksGithubInfoMutation>;
};

export type SecurityAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type SecurityGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type SecurityMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<SecurityAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<SecurityGithubInfoMutation>;
};

export type ImagesAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type ImagesGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type ImagesMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<ImagesAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<ImagesGithubInfoMutation>;
};

export type AnalyticsAddOnThumbnailMutation = {
  title?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
};

export type AnalyticsGithubInfoMutation = {
  githubLink?: InputMaybe<Scalars['String']>;
  githubStars?: InputMaybe<Scalars['String']>;
};

export type AnalyticsMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  descriptionOfFreePlan?: InputMaybe<Scalars['String']>;
  siteLink?: InputMaybe<Scalars['String']>;
  pricingPage?: InputMaybe<Scalars['String']>;
  thumbnail?: InputMaybe<Scalars['String']>;
  addOnThumbnail?: InputMaybe<AnalyticsAddOnThumbnailMutation>;
  githubInfo?: InputMaybe<AnalyticsGithubInfoMutation>;
};

export type AuthenticationPartsFragment = { __typename?: 'Authentication', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'AuthenticationAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'AuthenticationGithubInfo', githubLink?: string | null, githubStars?: string | null } | null, comparisonInfo?: { __typename: 'AuthenticationComparisonInfo', monthlyActiveUsers?: string | null, emailAndPasswordAuth?: boolean | null, magicLinks?: boolean | null, socialLogins?: string | null, phoneNumberAuth?: string | null, anonymousAuthentication?: boolean | null, multiFactorAuthentication?: boolean | null, userInterfaceProvided?: boolean | null, customDomain?: boolean | null, noBrandWatermark?: boolean | null } | null };

export type WebHostingPartsFragment = { __typename?: 'WebHosting', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'WebHostingAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'WebHostingGithubInfo', githubLink?: string | null, githubStars?: string | null } | null, comparisonInfo?: { __typename: 'WebHostingComparisonInfo', siteLimit?: string | null, freeBandwidth?: string | null, additionalBandwidthCost?: string | null, freeBuildMinutes?: string | null, concurrentBuilds?: string | null, deploymentPreview?: boolean | null, serverlessFunctionExecution?: string | null, serverlessFunctionInvocations?: string | null, serverlessFunctionExecutionTimeout?: string | null, edgeFunctionExecution?: string | null, globalCdn?: boolean | null, customHeaders?: boolean | null, https?: boolean | null, ddosProtection?: boolean | null } | null };

export type DatabasesPartsFragment = { __typename?: 'Databases', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'DatabasesAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'DatabasesGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type BaasPartsFragment = { __typename?: 'Baas', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'BaasAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'BaasGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type CloudProvidersPartsFragment = { __typename?: 'CloudProviders', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'CloudProvidersAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'CloudProvidersGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type FrameworksPartsFragment = { __typename?: 'Frameworks', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'FrameworksAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'FrameworksGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type SecurityPartsFragment = { __typename?: 'Security', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'SecurityAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'SecurityGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type ImagesPartsFragment = { __typename?: 'Images', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'ImagesAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'ImagesGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type AnalyticsPartsFragment = { __typename?: 'Analytics', title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, addOnThumbnail?: { __typename: 'AnalyticsAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'AnalyticsGithubInfo', githubLink?: string | null, githubStars?: string | null } | null };

export type AuthenticationQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type AuthenticationQuery = { __typename?: 'Query', authentication: { __typename?: 'Authentication', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'AuthenticationAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'AuthenticationGithubInfo', githubLink?: string | null, githubStars?: string | null } | null, comparisonInfo?: { __typename: 'AuthenticationComparisonInfo', monthlyActiveUsers?: string | null, emailAndPasswordAuth?: boolean | null, magicLinks?: boolean | null, socialLogins?: string | null, phoneNumberAuth?: string | null, anonymousAuthentication?: boolean | null, multiFactorAuthentication?: boolean | null, userInterfaceProvided?: boolean | null, customDomain?: boolean | null, noBrandWatermark?: boolean | null } | null } };

export type AuthenticationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<AuthenticationFilter>;
}>;


export type AuthenticationConnectionQuery = { __typename?: 'Query', authenticationConnection: { __typename?: 'AuthenticationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AuthenticationConnectionEdges', cursor: string, node?: { __typename?: 'Authentication', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'AuthenticationAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'AuthenticationGithubInfo', githubLink?: string | null, githubStars?: string | null } | null, comparisonInfo?: { __typename: 'AuthenticationComparisonInfo', monthlyActiveUsers?: string | null, emailAndPasswordAuth?: boolean | null, magicLinks?: boolean | null, socialLogins?: string | null, phoneNumberAuth?: string | null, anonymousAuthentication?: boolean | null, multiFactorAuthentication?: boolean | null, userInterfaceProvided?: boolean | null, customDomain?: boolean | null, noBrandWatermark?: boolean | null } | null } | null } | null> | null } };

export type WebHostingQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type WebHostingQuery = { __typename?: 'Query', webHosting: { __typename?: 'WebHosting', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'WebHostingAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'WebHostingGithubInfo', githubLink?: string | null, githubStars?: string | null } | null, comparisonInfo?: { __typename: 'WebHostingComparisonInfo', siteLimit?: string | null, freeBandwidth?: string | null, additionalBandwidthCost?: string | null, freeBuildMinutes?: string | null, concurrentBuilds?: string | null, deploymentPreview?: boolean | null, serverlessFunctionExecution?: string | null, serverlessFunctionInvocations?: string | null, serverlessFunctionExecutionTimeout?: string | null, edgeFunctionExecution?: string | null, globalCdn?: boolean | null, customHeaders?: boolean | null, https?: boolean | null, ddosProtection?: boolean | null } | null } };

export type WebHostingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<WebHostingFilter>;
}>;


export type WebHostingConnectionQuery = { __typename?: 'Query', webHostingConnection: { __typename?: 'WebHostingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WebHostingConnectionEdges', cursor: string, node?: { __typename?: 'WebHosting', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'WebHostingAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'WebHostingGithubInfo', githubLink?: string | null, githubStars?: string | null } | null, comparisonInfo?: { __typename: 'WebHostingComparisonInfo', siteLimit?: string | null, freeBandwidth?: string | null, additionalBandwidthCost?: string | null, freeBuildMinutes?: string | null, concurrentBuilds?: string | null, deploymentPreview?: boolean | null, serverlessFunctionExecution?: string | null, serverlessFunctionInvocations?: string | null, serverlessFunctionExecutionTimeout?: string | null, edgeFunctionExecution?: string | null, globalCdn?: boolean | null, customHeaders?: boolean | null, https?: boolean | null, ddosProtection?: boolean | null } | null } | null } | null> | null } };

export type DatabasesQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type DatabasesQuery = { __typename?: 'Query', databases: { __typename?: 'Databases', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'DatabasesAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'DatabasesGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type DatabasesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DatabasesFilter>;
}>;


export type DatabasesConnectionQuery = { __typename?: 'Query', databasesConnection: { __typename?: 'DatabasesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DatabasesConnectionEdges', cursor: string, node?: { __typename?: 'Databases', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'DatabasesAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'DatabasesGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export type BaasQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type BaasQuery = { __typename?: 'Query', baas: { __typename?: 'Baas', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'BaasAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'BaasGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type BaasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<BaasFilter>;
}>;


export type BaasConnectionQuery = { __typename?: 'Query', baasConnection: { __typename?: 'BaasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BaasConnectionEdges', cursor: string, node?: { __typename?: 'Baas', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'BaasAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'BaasGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export type CloudProvidersQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type CloudProvidersQuery = { __typename?: 'Query', cloudProviders: { __typename?: 'CloudProviders', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'CloudProvidersAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'CloudProvidersGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type CloudProvidersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<CloudProvidersFilter>;
}>;


export type CloudProvidersConnectionQuery = { __typename?: 'Query', cloudProvidersConnection: { __typename?: 'CloudProvidersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CloudProvidersConnectionEdges', cursor: string, node?: { __typename?: 'CloudProviders', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'CloudProvidersAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'CloudProvidersGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export type FrameworksQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type FrameworksQuery = { __typename?: 'Query', frameworks: { __typename?: 'Frameworks', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'FrameworksAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'FrameworksGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type FrameworksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<FrameworksFilter>;
}>;


export type FrameworksConnectionQuery = { __typename?: 'Query', frameworksConnection: { __typename?: 'FrameworksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FrameworksConnectionEdges', cursor: string, node?: { __typename?: 'Frameworks', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'FrameworksAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'FrameworksGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export type SecurityQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type SecurityQuery = { __typename?: 'Query', security: { __typename?: 'Security', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'SecurityAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'SecurityGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type SecurityConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<SecurityFilter>;
}>;


export type SecurityConnectionQuery = { __typename?: 'Query', securityConnection: { __typename?: 'SecurityConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SecurityConnectionEdges', cursor: string, node?: { __typename?: 'Security', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'SecurityAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'SecurityGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export type ImagesQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type ImagesQuery = { __typename?: 'Query', images: { __typename?: 'Images', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'ImagesAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'ImagesGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type ImagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<ImagesFilter>;
}>;


export type ImagesConnectionQuery = { __typename?: 'Query', imagesConnection: { __typename?: 'ImagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ImagesConnectionEdges', cursor: string, node?: { __typename?: 'Images', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'ImagesAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'ImagesGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export type AnalyticsQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type AnalyticsQuery = { __typename?: 'Query', analytics: { __typename?: 'Analytics', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'AnalyticsAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'AnalyticsGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } };

export type AnalyticsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<AnalyticsFilter>;
}>;


export type AnalyticsConnectionQuery = { __typename?: 'Query', analyticsConnection: { __typename?: 'AnalyticsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AnalyticsConnectionEdges', cursor: string, node?: { __typename?: 'Analytics', id: string, title: string, description: string, descriptionOfFreePlan?: string | null, siteLink: string, pricingPage?: string | null, thumbnail: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addOnThumbnail?: { __typename: 'AnalyticsAddOnThumbnail', title?: string | null, image?: string | null } | null, githubInfo?: { __typename: 'AnalyticsGithubInfo', githubLink?: string | null, githubStars?: string | null } | null } | null } | null> | null } };

export const AuthenticationPartsFragmentDoc = gql`
    fragment AuthenticationParts on Authentication {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
  comparisonInfo {
    __typename
    monthlyActiveUsers
    emailAndPasswordAuth
    magicLinks
    socialLogins
    phoneNumberAuth
    anonymousAuthentication
    multiFactorAuthentication
    userInterfaceProvided
    customDomain
    noBrandWatermark
  }
}
    `;
export const WebHostingPartsFragmentDoc = gql`
    fragment WebHostingParts on WebHosting {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
  comparisonInfo {
    __typename
    siteLimit
    freeBandwidth
    additionalBandwidthCost
    freeBuildMinutes
    concurrentBuilds
    deploymentPreview
    serverlessFunctionExecution
    serverlessFunctionInvocations
    serverlessFunctionExecutionTimeout
    edgeFunctionExecution
    globalCdn
    customHeaders
    https
    ddosProtection
  }
}
    `;
export const DatabasesPartsFragmentDoc = gql`
    fragment DatabasesParts on Databases {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const BaasPartsFragmentDoc = gql`
    fragment BaasParts on Baas {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const CloudProvidersPartsFragmentDoc = gql`
    fragment CloudProvidersParts on CloudProviders {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const FrameworksPartsFragmentDoc = gql`
    fragment FrameworksParts on Frameworks {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const SecurityPartsFragmentDoc = gql`
    fragment SecurityParts on Security {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const ImagesPartsFragmentDoc = gql`
    fragment ImagesParts on Images {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const AnalyticsPartsFragmentDoc = gql`
    fragment AnalyticsParts on Analytics {
  title
  description
  descriptionOfFreePlan
  siteLink
  pricingPage
  thumbnail
  addOnThumbnail {
    __typename
    title
    image
  }
  githubInfo {
    __typename
    githubLink
    githubStars
  }
}
    `;
export const AuthenticationDocument = gql`
    query authentication($relativePath: String!) {
  authentication(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AuthenticationParts
  }
}
    ${AuthenticationPartsFragmentDoc}`;
export const AuthenticationConnectionDocument = gql`
    query authenticationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AuthenticationFilter) {
  authenticationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AuthenticationParts
      }
    }
  }
}
    ${AuthenticationPartsFragmentDoc}`;
export const WebHostingDocument = gql`
    query webHosting($relativePath: String!) {
  webHosting(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WebHostingParts
  }
}
    ${WebHostingPartsFragmentDoc}`;
export const WebHostingConnectionDocument = gql`
    query webHostingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WebHostingFilter) {
  webHostingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WebHostingParts
      }
    }
  }
}
    ${WebHostingPartsFragmentDoc}`;
export const DatabasesDocument = gql`
    query databases($relativePath: String!) {
  databases(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DatabasesParts
  }
}
    ${DatabasesPartsFragmentDoc}`;
export const DatabasesConnectionDocument = gql`
    query databasesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DatabasesFilter) {
  databasesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DatabasesParts
      }
    }
  }
}
    ${DatabasesPartsFragmentDoc}`;
export const BaasDocument = gql`
    query baas($relativePath: String!) {
  baas(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BaasParts
  }
}
    ${BaasPartsFragmentDoc}`;
export const BaasConnectionDocument = gql`
    query baasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BaasFilter) {
  baasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BaasParts
      }
    }
  }
}
    ${BaasPartsFragmentDoc}`;
export const CloudProvidersDocument = gql`
    query cloudProviders($relativePath: String!) {
  cloudProviders(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CloudProvidersParts
  }
}
    ${CloudProvidersPartsFragmentDoc}`;
export const CloudProvidersConnectionDocument = gql`
    query cloudProvidersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CloudProvidersFilter) {
  cloudProvidersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CloudProvidersParts
      }
    }
  }
}
    ${CloudProvidersPartsFragmentDoc}`;
export const FrameworksDocument = gql`
    query frameworks($relativePath: String!) {
  frameworks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FrameworksParts
  }
}
    ${FrameworksPartsFragmentDoc}`;
export const FrameworksConnectionDocument = gql`
    query frameworksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FrameworksFilter) {
  frameworksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FrameworksParts
      }
    }
  }
}
    ${FrameworksPartsFragmentDoc}`;
export const SecurityDocument = gql`
    query security($relativePath: String!) {
  security(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SecurityParts
  }
}
    ${SecurityPartsFragmentDoc}`;
export const SecurityConnectionDocument = gql`
    query securityConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SecurityFilter) {
  securityConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SecurityParts
      }
    }
  }
}
    ${SecurityPartsFragmentDoc}`;
export const ImagesDocument = gql`
    query images($relativePath: String!) {
  images(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ImagesParts
  }
}
    ${ImagesPartsFragmentDoc}`;
export const ImagesConnectionDocument = gql`
    query imagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ImagesFilter) {
  imagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ImagesParts
      }
    }
  }
}
    ${ImagesPartsFragmentDoc}`;
export const AnalyticsDocument = gql`
    query analytics($relativePath: String!) {
  analytics(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AnalyticsParts
  }
}
    ${AnalyticsPartsFragmentDoc}`;
export const AnalyticsConnectionDocument = gql`
    query analyticsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AnalyticsFilter) {
  analyticsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AnalyticsParts
      }
    }
  }
}
    ${AnalyticsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      authentication(variables: AuthenticationQueryVariables, options?: C): Promise<{data: AuthenticationQuery, variables: AuthenticationQueryVariables, query: string}> {
        return requester<{data: AuthenticationQuery, variables: AuthenticationQueryVariables, query: string}, AuthenticationQueryVariables>(AuthenticationDocument, variables, options);
      },
    authenticationConnection(variables?: AuthenticationConnectionQueryVariables, options?: C): Promise<{data: AuthenticationConnectionQuery, variables: AuthenticationConnectionQueryVariables, query: string}> {
        return requester<{data: AuthenticationConnectionQuery, variables: AuthenticationConnectionQueryVariables, query: string}, AuthenticationConnectionQueryVariables>(AuthenticationConnectionDocument, variables, options);
      },
    webHosting(variables: WebHostingQueryVariables, options?: C): Promise<{data: WebHostingQuery, variables: WebHostingQueryVariables, query: string}> {
        return requester<{data: WebHostingQuery, variables: WebHostingQueryVariables, query: string}, WebHostingQueryVariables>(WebHostingDocument, variables, options);
      },
    webHostingConnection(variables?: WebHostingConnectionQueryVariables, options?: C): Promise<{data: WebHostingConnectionQuery, variables: WebHostingConnectionQueryVariables, query: string}> {
        return requester<{data: WebHostingConnectionQuery, variables: WebHostingConnectionQueryVariables, query: string}, WebHostingConnectionQueryVariables>(WebHostingConnectionDocument, variables, options);
      },
    databases(variables: DatabasesQueryVariables, options?: C): Promise<{data: DatabasesQuery, variables: DatabasesQueryVariables, query: string}> {
        return requester<{data: DatabasesQuery, variables: DatabasesQueryVariables, query: string}, DatabasesQueryVariables>(DatabasesDocument, variables, options);
      },
    databasesConnection(variables?: DatabasesConnectionQueryVariables, options?: C): Promise<{data: DatabasesConnectionQuery, variables: DatabasesConnectionQueryVariables, query: string}> {
        return requester<{data: DatabasesConnectionQuery, variables: DatabasesConnectionQueryVariables, query: string}, DatabasesConnectionQueryVariables>(DatabasesConnectionDocument, variables, options);
      },
    baas(variables: BaasQueryVariables, options?: C): Promise<{data: BaasQuery, variables: BaasQueryVariables, query: string}> {
        return requester<{data: BaasQuery, variables: BaasQueryVariables, query: string}, BaasQueryVariables>(BaasDocument, variables, options);
      },
    baasConnection(variables?: BaasConnectionQueryVariables, options?: C): Promise<{data: BaasConnectionQuery, variables: BaasConnectionQueryVariables, query: string}> {
        return requester<{data: BaasConnectionQuery, variables: BaasConnectionQueryVariables, query: string}, BaasConnectionQueryVariables>(BaasConnectionDocument, variables, options);
      },
    cloudProviders(variables: CloudProvidersQueryVariables, options?: C): Promise<{data: CloudProvidersQuery, variables: CloudProvidersQueryVariables, query: string}> {
        return requester<{data: CloudProvidersQuery, variables: CloudProvidersQueryVariables, query: string}, CloudProvidersQueryVariables>(CloudProvidersDocument, variables, options);
      },
    cloudProvidersConnection(variables?: CloudProvidersConnectionQueryVariables, options?: C): Promise<{data: CloudProvidersConnectionQuery, variables: CloudProvidersConnectionQueryVariables, query: string}> {
        return requester<{data: CloudProvidersConnectionQuery, variables: CloudProvidersConnectionQueryVariables, query: string}, CloudProvidersConnectionQueryVariables>(CloudProvidersConnectionDocument, variables, options);
      },
    frameworks(variables: FrameworksQueryVariables, options?: C): Promise<{data: FrameworksQuery, variables: FrameworksQueryVariables, query: string}> {
        return requester<{data: FrameworksQuery, variables: FrameworksQueryVariables, query: string}, FrameworksQueryVariables>(FrameworksDocument, variables, options);
      },
    frameworksConnection(variables?: FrameworksConnectionQueryVariables, options?: C): Promise<{data: FrameworksConnectionQuery, variables: FrameworksConnectionQueryVariables, query: string}> {
        return requester<{data: FrameworksConnectionQuery, variables: FrameworksConnectionQueryVariables, query: string}, FrameworksConnectionQueryVariables>(FrameworksConnectionDocument, variables, options);
      },
    security(variables: SecurityQueryVariables, options?: C): Promise<{data: SecurityQuery, variables: SecurityQueryVariables, query: string}> {
        return requester<{data: SecurityQuery, variables: SecurityQueryVariables, query: string}, SecurityQueryVariables>(SecurityDocument, variables, options);
      },
    securityConnection(variables?: SecurityConnectionQueryVariables, options?: C): Promise<{data: SecurityConnectionQuery, variables: SecurityConnectionQueryVariables, query: string}> {
        return requester<{data: SecurityConnectionQuery, variables: SecurityConnectionQueryVariables, query: string}, SecurityConnectionQueryVariables>(SecurityConnectionDocument, variables, options);
      },
    images(variables: ImagesQueryVariables, options?: C): Promise<{data: ImagesQuery, variables: ImagesQueryVariables, query: string}> {
        return requester<{data: ImagesQuery, variables: ImagesQueryVariables, query: string}, ImagesQueryVariables>(ImagesDocument, variables, options);
      },
    imagesConnection(variables?: ImagesConnectionQueryVariables, options?: C): Promise<{data: ImagesConnectionQuery, variables: ImagesConnectionQueryVariables, query: string}> {
        return requester<{data: ImagesConnectionQuery, variables: ImagesConnectionQueryVariables, query: string}, ImagesConnectionQueryVariables>(ImagesConnectionDocument, variables, options);
      },
    analytics(variables: AnalyticsQueryVariables, options?: C): Promise<{data: AnalyticsQuery, variables: AnalyticsQueryVariables, query: string}> {
        return requester<{data: AnalyticsQuery, variables: AnalyticsQueryVariables, query: string}, AnalyticsQueryVariables>(AnalyticsDocument, variables, options);
      },
    analyticsConnection(variables?: AnalyticsConnectionQueryVariables, options?: C): Promise<{data: AnalyticsConnectionQuery, variables: AnalyticsConnectionQueryVariables, query: string}> {
        return requester<{data: AnalyticsConnectionQuery, variables: AnalyticsConnectionQueryVariables, query: string}, AnalyticsConnectionQueryVariables>(AnalyticsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    const data = await client.request({
      query: doc,
      variables: vars,
    });

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "http://localhost:4001/graphql", queries }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

  